app/models.py
# -*- coding:utf-8 -*-

from . import db, login_manager
from flask_login import UserMixin, AnonymousUserMixin
from datetime import datetime
from markdown import markdown


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    users = db.relationship('User', backref="role")

    @staticmethod
    def seed():
        db.session.add_all(map(lambda r: Role(name=r), ['Guests', 'Administrators']))
        db.session.commit()


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    email = db.Column(db.String)
    password = db.Column(db.String)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    posts = db.relationship('Post', backref='author')
    comments = db.relationship('Comment', backref='author')
    locale = db.Column(db.String, default='zh')

    @staticmethod
    def on_created(target, value, oldvalue, initiator):
        target.role = Role.query.filter_by(name='Guests').first()


class AnonymousUser(AnonymousUserMixin):
    @property
    def locale(self):
        return 'zh'

    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


db.event.listen(User.name, 'set', User.on_created)


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    body = db.Column(db.String)
    body_html = db.Column(db.String)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    comments = db.relationship('Comment', backref='post')
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    @staticmethod
    def on_body_changed(target, value, oldvalue, initiator):
        if value is None or (value is ''):
            target.body_html = ''
        else:
            target.body_html = markdown(value)


db.event.listen(Post.body, 'set', Post.on_body_changed)


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/main/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_pagedown.fields import PageDownField
from flask_babel import gettext as _


class PostForm(Form):
    title = StringField(label=_(u'标题'), validators=[DataRequired()])
    body = PageDownField(label=_(u'正文'), validators=[DataRequired()])
    submit = SubmitField(_(u'发表'))


class CommentForm(Form):
    body = PageDownField(label=_(u'评论'), validators=[DataRequired()])
    submit = SubmitField(_(u'发表'))

app/__init__.py
# -*- coding: utf-8 -*-

from flask import Flask, request
from os import path
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
from flask_pagedown import PageDown
from flask_gravatar import Gravatar
from flask_babel import Babel, gettext as _
from config import config

basedir = path.abspath(path.dirname(__file__))

babel = Babel()

# 这么做是为了解决app.py和models.py关于db的循环引用，将db独立出来之后分别被引用
db = SQLAlchemy()
pagedown = PageDown()
bootstrap = Bootstrap()
login_manager = LoginManager()

# one,'basic','strong'以提供不同的安全等级,一般设置strong,如果发现异常会登出用户
login_manager.session_protection = 'strong'

# 未登录访问鉴权页面时，重新定向到登录页面
login_manager.login_view = 'auth.login'


def create_app(config_name='default'):

    # app是Flask的实例，它接收包或者模块的名字作为参数
    app = Flask(__name__)

    # 默认的模式是development，除此之外还有testing & production
    app.config.from_object(config[config_name])

    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)

    babel.init_app(app)
    Gravatar(app, size=64)

    from .auth import auth as auth_blueprint
    from .main import main as main_blueprint

    app.register_blueprint(auth_blueprint, url_perfix='/auth')
    app.register_blueprint(main_blueprint, static_folder='static')

    @app.template_test('current_link')
    def is_current_link(link):
        return link == request.path

    @babel.localeselector
    def get_locale():
        return current_user.locale

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
# -*- coding: utf-8 -*-

from flask import render_template, request, flash, redirect, url_for, current_app, abort
from . import main
from .. import db
from ..models import Post, Comment
from flask_login import login_required, current_user
from .forms import CommentForm, PostForm
from flask_babel import gettext as _


# 使用程序实例提供的app.route修饰器，把修饰的函数注册为路由
@main.route('/')
def index():
    # 从request的参数中获取参数page的值，如果参数不存在那么返回默认值1，type=int保证返回的默认值是整型数字
    page_index = request.args.get('page', 1, type=int)

    # 第一个参数表示我们要查询的页数，这里用了上面获取的url的参数；
    # 第二个参数是每页显示的数量，我们这里设置成了1，如果不设置默认显示20条；
    # 第三个参数如果设置成True，当请求的页数超过了总的页数范围，就会返回一个404错误，如果设为False，就会返回一个空列表
    pagination = Post.query.paginate(page_index, per_page=20, error_out=False)
    posts = pagination.items
    return render_template("index.html",
                           title=_(u'欢迎来到Vincent--Gao的博客'),
                           posts=posts,
                           pagination=pagination)


@main.route('/about')
def about():
    return render_template("about.html", title=u'关于')


@main.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    # 对于不存在的条目返回一个404错误
    post = Post.query.get_or_404(id)

    form = CommentForm()

    # 验证用户名和密码
    if form.validate_on_submit():
        comment = Comment(author=current_user,
                          body=form.body.data,
                          post=post)
        db.session.add(comment)
        db.session.commit()

    return render_template('posts/detail.html',
                           title=post.title,
                           form=form,
                           post=post)


@main.route('/edit', methods=['GET', 'POST'])
@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    form = PostForm()

    if id == 0:
        post = Post(author=current_user)
    else:
        post = Post.query.get_or_404(id)

    if form.validate_on_submit():
        post.body = form.body.data
        post.title = form.title.data

        db.session.add(post)
        db.session.commit()

        return redirect(url_for('.post', id=post.id))

    form.title.data = post.title
    form.body.data = post.body

    title = _(u'添加新文章')
    if id > 0:
        title = _(u'编辑 - %(title)', title=post.title)

    return render_template('posts/edit.html',
                           title=title,
                           form=form,
                           post=post)


# To shutdown the server you simply make a HTTP request to shutdown.
@main.route('/shutdown')
def shutdown():
    if not current_app.testing:
        abort(404)

    shutdown = request.environ.get('werkzeug.server.shutdown')
    if not shutdown:
        abort(500)

    shutdown()
    return u'正在关闭服务端进程...'

app/templates/about.html
{% extends 'base.html' %}
{% block page_body %}
    <div class="container">
    </div>
{% endblock %}

app/templates/base.html
{% extends 'bootstrapBase.html' %}

{% block title %}{{ title }}{% endblock %}

{% block head %}
    {{ super() }}
    {% include 'includes/_head.html' %}
{% endblock %}


{% block navbar %}
    {% include 'includes/_navbar.html' %}
{% endblock %}

{% block content %}
    {{ super() }}
    {% block header %}
        <header>
            <div class="page-header">
                <div class="container">
                    <h1>{{ title }}</h1>
                </div>
            </div>
        </header>
    {% endblock %}
    {% block page_body %}
    {% endblock %}
{% endblock %}

{% block footer %}
    {% include 'includes/_footer.html' %}
{% endblock %}

{% block body_attribs %}
    background="../static/spurs3.jpg"
{% endblock body_attribs %}

app/templates/bootstrapBase.html
{% block doc -%}
    <!DOCTYPE html>
    <html{% block html_attribs %}{% endblock html_attribs %}>
    {%- block html %}
        <head>
            {%- block head %}
                <title>{% block title %}{{ title|default }}{% endblock title %}</title>

                {%- block metas %}
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                {%- endblock metas %}

                {%- block styles %}
                    <!-- Bootstrap -->
                    <link href="{{ bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap') }}" rel="stylesheet">
                {%- endblock styles %}
            {%- endblock head %}
        </head>
        <body{% block body_attribs %}{% endblock body_attribs %}>
        {% block body -%}
            {% block navbar %}
            {%- endblock navbar %}
            {% block content -%}
            {%- endblock content %}
            {% block footer %}
            {%- endblock footer %}

            {% block scripts %}
                <script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
                <script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
            {%- endblock scripts %}
        {%- endblock body %}
        </body>
    {%- endblock html %}
    </html>
{% endblock doc -%}

app/templates/includes/_footer.html
<h3 align="center">
    Copyright 2018 by <a href="gaohaojun.cn">GaoHaojun</a>
</h3>

app/templates/includes/_head.html
{# 告知浏览器此页面属于什么字符编码格式 #}
<meta charset="UTF-8">

{# url_for()函数最简单的用法是以视图函数名作为参数，返回对应的url，还可以用作加载静态文件 #}
{# rel是relationship的英文缩写，它描述了当前页面与href所指定文档的关系 #}
{# rel="stylesheet"就是声明此文件为样式表文件，告诉浏览器你link过来的是一个样式 #}
<link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet">

{# 定义了一个名为title的block #}
<title>{% block title %}{% endblock %}</title>

app/templates/includes/_navbar.html
{# 静态的顶部导航条 #}
{# 创建一个最小高度为50px的条形容器（.navbar），相对于于浏览器定位(.navbar-fixed-top)，确定导航栏的配色（.navbar-default） #}
<nav class="navbar navbar-default navbar-static-top">
    {# 自适应屏幕宽度布局，即满屏显示#}
    <div class="container">
        {# 在pc端时，浏览器宽度足够，此div仅作为一个小的块级元素存在#}
        {#        在移动端时，由于屏幕宽度不够，故将导航栏的其他元素以下拉菜单的形式实现，此div单独填满父容器#}
        <div class="navbar-header">
            {#            在菜单前面添加一个标题（文字字号比其它文字稍大一些）#}
            <a class="navbar-brand">高浩峻</a>
            {#            在最右侧画了一个圆角矩形,并且在pc端不显示#}
            <button type="button"
                    class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#navbar"
                    aria-controls="navbar"
                    aria-expanded="false">
                {#                除了屏幕阅读器外，其他设备上隐藏该元素，这个是用于帮助残障人士阅读的#}
                <span class="sr-only">Toggle navigation</span>
                {#                icon-bar负责在button盒子里画横线#}
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse"
             id="navbar">
            <ul class="nav navbar-nav">
                <li {% if url_for('main.index') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.index') }}" title="{{ _("主页") }}">{{ _("主页") }}</a>
                </li>
                <li {% if url_for('main.about') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.about') }}" title="{{ _("关于") }}">{{ _("关于") }}</a>
                </li>
            </ul>
            {#            向右对其#}
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                    <li><a href="#">{{ current_user.name }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ _("退出") }}</a></li>
                {% else %}
                    <li>
                        <a href="{{ url_for('auth.login') }}">
                            <span class="glyphicon glyphicon-user"></span>
                            {{ _("登录") }}
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.register') }}">
                            <span class="glyphicon glyphicon-log-in"></span>
                            {{ _("注册") }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

app/templates/index.html
{% extends 'base.html' %}
{% from "bootstrap/pagination.html" import render_pagination %}

{% block page_body %}
    <div class="container">
        <a href="{{ url_for('main.edit') }}" class="btn btn-primary">发表新文章</a>
    </div>
    <div class="container">
        {% for post in posts %}
            <h2>
                <a href="{{ url_for('main.post', id = post.id) }}">{{ post.title }}</a>
            </h2>
            <div>
                {{ post.body_html | safe }}
            </div>
        {% endfor %}

        {% if pagination %}
                {{ render_pagination(pagination) }}
        {% endif %}
    </div>
{% endblock %}


app/templates/login.html
{% extends 'base.html' %}
{# 导入的 bootstrap/wtf.html文件中定义了一个使用Bootstrap渲染Falsk-WTF表单对象的辅助函数 #}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_body %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert-info">
                {{ message }}
            </div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/posts/detail.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_body %}
    <div class="container">
        <span>作者:{{ post.author.name }}</span> <span>发表日期:{{ post.created }}</span>
        <hr>

        {# 正文 #}
        <div>
            {{ post.body_html | safe }}
        </div>

        {# 操作连接 #}
        <h3>评论</h3>

        {# 发表评论 #}
        <div>
            {{ wtf.quick_form(form) }}
        </div>

        {# 评论列表 #}
        {% for comment in post.comments | sort(attribute='created',reverse=True) %}
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object img-circle" src="{{ comment.author.email | gravatar }}">
                    </a>
                </div>
                <div class="media-body">
                    <small class="text-muted">{{ comment.created }}</small>
                    <div>{{ comment.body }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/posts/edit.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block scripts %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
{% endblock %}

{% block body %}
    <div class="container">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title(class="form-control", placeholder="请输入文章标题") }}
            </div>
            <div class="form-group">
                {{ form.body(only_input=True, rows=10, class="form-control") }}
            </div>
            <div>
                {{ form.body(only_preview=True) }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block page_body %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert-info">{{ message }}</div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>文件上传</h1>

<form action=""
      method="post"
      enctype=multipart/form-data>
    <p><input type=file name=file>
        <input type=submit value=Upload></p>
</form>
</body>
</html>